### ISSUE TITLE
Simultaneous requests from multiple Prometheus scrapers

### ISSUE THREAD

**Issue by neilschelly** [oracle/weblogic-monitoring-exporter#136]
We have two redundant Prometheus servers that each independently scrape all our targets. At any given time, one of them will get a successful response from the wls-exporter REST endpoint and the other will get a 401/Unauthorized response. They will trade places every so often. Both requests are authenticated with the same credentials.

It almost appears that there is some rate-limiting going on where if two requests come in too close together, the first will work, and the second will yield the 401. If I try again with a curl command shortly afterward from the machine getting a 401, it will usually work fine only a few seconds later.

I cannot find any configurations (defaults or otherwise) in our WebLogic Server that suggest any kind of rate-limiting is in place. Is it possible the exporter itself has some internal rate-limiting creating this fault?

I've got wls-exporter setup in the most generic way possible. My conifg.yml is just

```yaml
metricsNameSnakeCase: true
domainQualifier: true
#restPort: 7001
queries:
- key: name
  keyName: server
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: invocationTotalCount
```
