### ISSUE TITLE
Managed server name as key

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-monitoring-exporter#14]
I could not figure out how to add the managed server name as an attribute/key to each exported stat.  For example, if I have a JMS destination on a cluster of two managed servers, how can I distinguish the stats for each managed server?  If the queue is backing up on one server, and not the other, there is nothing in the data that tells me which server has the issue.  JMS destinations is only an example, and this issue is not limited to JMS.  There needs to be a way to add the managed server name to the keys of the exported data.

**Comment by russgold** [comment]
From Tom Moreau:

GET <ms host/port>/management/weblogic/latest/serverRuntime?fields=name

**Comment by russgold** [comment]
Performance metrics currently report host and port. Will that work if added to other metrics?

**Comment by russgold** [comment]
The server name is found in the ```name``` field of the ServerRuntime mbean, and can be added to metrics as follows:

```
metricsNameSnakeCase: true
queries:
- key: name
  keyName: server
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [openSessionsHighCount, openSessionsCurrentCount]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
```
