### ISSUE TITLE
Suggestion: Gather Health and State Metrics

### ISSUE THREAD

**Issue by eagle-rr** [oracle/weblogic-monitoring-exporter#151]
Allow for polling of "state" (ex.: "RUNNING") and "overallHealthState:state" (ex.: "ok") to values which can be reported/gathered by prometheus (Ex.: 1 = RUNNING; 2 = WARNING; 3 = STOPPED).  This would be valuable when reporting status of managed server, deployed applications, jdbc connections, etc.

**Comment by mriccell** [comment]
Have you considered using the WebLogic Remote Console to gather this kind of monitoring information?  Please refer to https://github.com/oracle/weblogic-remote-console

**Comment by eagle-rr** [comment]
I do not see a method of using weblogic-remote-console as an exporter which Prometheus can scrape.  Basically, it would be good to get various WebLogic's component's health available to be scraped into Prometheus and then we can alert via AlertManager (ex.: via pagerduty to operator).

**Comment by mriccell** [comment]
We will capture this requirement.

**Comment by russgold** [comment]
This is now in the main branch and will be included in the next release. With this config
```
queries:
- prefix: wls_server_
  key: name
  keyName: location
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: wls_webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount]
      stringValues:
        status: [deployed, undeployed]
```

we now get metrics like
```
wls_webapp_config_status{domain="mydomain",location="myserver",app="wls-exporter",name="myserver_/wls-exporter"} 0
```
