### ISSUE TITLE
sidecar weblogic-monitoring-exporter fails to update configuration

### ISSUE THREAD

**Issue by brahankv** [oracle/weblogic-monitoring-exporter#152]
Tried to update the sidecar weblogic-monitoring-exporter configuration with curl

```
$ curl -X PUT -i -u user:password -H "content-type: application/yaml" --data-binary def.yml http://localhost:8080/configuration
```
failed with the following error,
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain
Date: Wed, 2 Jun 2021 11:39:26 GMT
transfer-encoding: chunked
connection: keep-alive

Configuration is not in YAML format
```
The configuration used is,
```
host: soainfra-soa-server1
port: 8001
domainQualifier: true
metricsNameSnakeCase: true
restPort: 8001
queries:
- key: name
  keyName: server
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: invocationTotalCount
```
The configuration is updated with host & port fetched from the documentation - https://github.com/oracle/weblogic-monitoring-exporter#configuration
Can you please let me know the issue with the configuration?
