### ISSUE TITLE
no main manifest attribute, in wls-exporter-core-2.0.3.jar

### ISSUE THREAD

**Issue by jijojohn1985** [oracle/weblogic-monitoring-exporter#158]
I am getting error **_no main manifest attribute, in wls-exporter-core-2.0.3.jar_** while running this. Please help if there is any thing wrong with the command syntax. also how do we provide the WebLogic credentials in yml file.

java -jar wls-exporter-core-2.0.3.jar 9405 /opt/pmexporter/wlstconfig.yml

wlstconfig.yml
=============
```
metricsNameSnakeCase: true
domainQualifier: true
restPort: 7012
queries:
- key: name
  keyName: server
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: invocationTotalCount
```
