### ISSUE TITLE
Failed to update sidecar configuration with CURL command

### ISSUE THREAD

**Issue by jingyuanli001** [oracle/weblogic-monitoring-exporter#209]
Hi, I am trying to setup a sidecar exporter with docker.
The sidecar exporter with initial setting is deployed successfully, and I received message when I visit the page hostname:8086

```
Current Configuration

hostName: hostname
port: 7001
queries:
```
I tried to update the configuration with curl command
`curl -X PUT -i -u wlsusername:wlspassword -H "content-type: application/yaml" --data-binary "@./wlsexporter_conf.yaml" http://hostname:8086/configuration`
and I received

```
HTTP/1.1 200 OK
Date: Thu, 29 Sep 2022 23:39:32 GMT
connection: keep-alive
content-length: 0
```
but nothing in the site hostname:port changes, and I am getting the same message as shown in the first code block. So I wonder what could be the reason for this failure.  The configuration file that I am trying to upload is
```
metricsNameSnakeCase: true
queries:
- applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount, openSessionsCurrentCount, sessionsOpenedTotalCount, sessionCookieMaxAgeSecs, sessionInvalidationIntervalSecs, sessionTimeoutSecs, singleThreadedServletPoolSize, sessionIDLength, servletReloadCheckSecs, jSPPageCheckSecs]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: [invocationTotalCount, reloadTotal, executionTimeAverage, poolMaxCapacity, executionTimeTotal, reloadTotalCount, executionTimeHigh, executionTimeLow]
- JVMRuntime:
    key: name
    values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, uptime, processCpuLoad]
```
