### ISSUE TITLE
Proposal: Query of the HealthState

### ISSUE THREAD

**Issue by augeivv** [oracle/weblogic-monitoring-exporter#370]
Apparently there has been the same request from others in the past, but without a solution.
We would like to know the HealthState or overallHealthState of the ServerRuntime and ApplicationRuntime. 

https://github.com/oracle/weblogic-monitoring-exporter/blob/9b614a896fb9a9c7d05cf63c747b730fc3dedd56/samples/configurations/healthState.yml#L10

Here is an example of the JTARuntime. But this one does not seem to work. Is there a solution for this?

**Comment by augeivv** [comment]
Hello,
is there any news on this topic yet?

**Comment by marinakog** [comment]
please change your configuration to : 
 - JTARuntime:
      prefix: wls_jta_
      key: name
      healthState:
        prefix: wls_jta_health_
        stringValues:
          state: [ok,failed,overloaded,critical,warn]

**Comment by piotr-skrobisz** [comment]
@augeivv I had a similar requirement to export HealthState and overallHealthState of the ServerRuntime. I came up with the following configuration to get those metrics.

```
metricsNameSnakeCase: true
queries:
- key: name
  prefix: wls_server_  
  stringValues:
    state: [SHUTDOWN,STARTING,RUNNING,STANDBY,FORCE_SUSPENDING,RESUMING,SHUTTING_DOWN,FAILED,UNKNOWN,FAILED_NOT_RESTARTABLE,ADMIN,FORCE_SHUTTING_DOWN]
  overallHealthState:
    prefix: wls_server_overallhealth_
    stringValues:
      state: [ok,failed,overloaded,critical,warn]
  healthState:
    prefix: wls_server_health_
    stringValues:
      state: [ok,failed,overloaded,critical,warn]   
```
