### ISSUE TITLE
restPort setting ignored when frontend host:port set on cluster

### ISSUE THREAD

**Issue by alkalineocelot** [oracle/weblogic-monitoring-exporter#47]
The restPort YAML file setting gets ignored for managed servers in Weblogic clusters with the frontend host and port values set for the cluster.  Note that the exporter uses the correct hostname of the managed server, but the port isn't set as per the restPort value in the exporter configuration file - the value defined in the frontend port field for the Weblogic cluster is used instead. In my case the cluster frontend port is port 80 but the managed server port is 8001. The exporter tries to connect to the REST API on myserver.foo.com:80 instead of myserver.foo.com:8001 even with the line "restPort: 8001" in the YAML file.

This does not affect managed servers in a cluster where the frontend host/port is not set - the correct managed server port is used.

**Comment by russgold** [comment]
What do you mean by "with the frontend host and port values set for the cluster"? Where is this being set?

**Comment by alkalineocelot** [comment]
Sorry - should have been clearer.
Via the Weblogic admin console: Environment > Clusters > [clustername from table] >Configuration tab > HTTP tab.
MBean attributes are ClusterMBean.FrontendHost, ClusterMBean.FrontendHTTPPort

**Comment by alkalineocelot** [comment]
I applied my (*very*) rusty java skills and made a little progress. it seems that this line:

 [`return Optional.ofNullable(config.getRestPort()).orElse(serverPort);`](https://github.com/oracle/weblogic-monitoring-exporter/blob/8f805265d083cedc3463d43b0d466493cd392aac/src/main/java/io/prometheus/wls/rest/LiveConfiguration.java#L98) 

always seems to return the value of `serverPort` when running in Weblogic. In my case this value is correct for the Admin Server and non clustered managed servers, but not correct for servers with the cluster frontend port set to something else - since `serverPort` gets set with the value got from the HttpServletRequest which is using the host and port set in the cluster's frontend host/port configuration (see my earlier comment with console location and MBean).

Having `restPort: xxxx` set in the YAML file doesn't seem to have an effect as the config.getRestPort() in the line above returns null all the time. I'm looking now to see why.

**Comment by russgold** [comment]
That's very surprising, as this works in plenty of environments. What version of the exporter are you using, and can you double-check your config file? It is easy to invalidate a yaml file with an unexpected space.

**Comment by alkalineocelot** [comment]
It is very odd. I built from a clone of master that I pulled down within the last couple of weeks (927208f1c2). This is the configuration I'm using at the moment:
```
metricsNameSnakeCase: true
restPort: 8001
queries:
- key: name
  keyName: server
  JVMRuntime:
    prefix: jvm_
    key: name
    values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, uptime, processCpuLoad]
  threadPoolRuntime:
    prefix: threadpool_
    key: name
    values: [executeThreadIdleCount, completedRequestCount, executeThreadTotalCount, stuckThreadCount, throughput, hoggingThreadCount, standbyThreadCount]
```
restPort is ignored. If I use it in a server where I don't need the restPort value to be different then it returns metrics fine. I'll keep looking and try to work out what I'm doing wrong.
