### ISSUE TITLE
Querying ServerRuntime

### ISSUE THREAD

**Issue by vikhyathk** [oracle/weblogic-monitoring-exporter#5]
I am trying to query the ServerRuntime MBean. I'm trying to pull out the OpenSocketsCurrentCount attribute. This is my configuration (Referring from DemoInputs.java)
```

metricsNameSnakeCase: true
queries:
-  serverRuntimes:
    key: name
    applicationRuntimes:
      key: name
      keyName: app
      componentRuntimes:
        type: WebAppComponentRuntime
        prefix: webapp_config_
        key: name
        servlets:
          prefix: weblogic_servlet_
          key: servletName

```
I'm not getting any metrics for the ServerRuntimes. 

Please help.
