### ISSUE TITLE
ER - String values should be exported as labels

### ISSUE THREAD

**Issue by rrpai** [oracle/weblogic-monitoring-exporter#62]
```
metricsNameSnakeCase: true
queries:
  - key: name
    keyName: location
    prefix: wls_server_
    applicationRuntimes:
      key: name
      keyName: app
      componentRuntimes:
        type: WebAppComponentRuntime
        prefix: webapp_config_
        key: name
        values: [status]
  - JDBCServiceRuntime:
      JDBCDataSourceRuntimeMBeans:
        prefix: jdbc_
        key: name
        keyName: app
        values: [state]
```

- State for jdbcDS and webapp are string values in mbean tree and can have values like 'Running', 'Failed', 'Overloaded', 'Suspended'
- As of now the exporter ignores the above values and we dont see any values
- Prometheus may not allow string to come as value, but instead it can be added as 'label'
eg
webapp_config_status { status = 'Running' }  = 1
webapp_config_status { status = 'Suspended' }  = 1

jdbc_state { state = 'Suspended' }  = 1

- we would like to use it for monitoring 'Oracle Content and Experience Cloud'  internally

Thanks
ratheesh.pai

**Comment by russgold** [comment]
You _could_ add them as labels, but each would wind up as a separate time series, which may not be what you want. See the discussion at https://github.com/prometheus/prometheus/issues/2227

**Comment by rrpai** [comment]
- I think there is a parallel in kubernetes world for pod 'phase' is exposed
kube_pod_status_phase{phase="Failed", pod="pod1"}  1
kube_pod_status_phase{phase="Succeeded", pod="pod1"}  0
kube_pod_status_phase{phase="Pending", pod="pod2"}  1
It can be something like that
Thanks

**Comment by benridley** [comment]
This would be a useful addition to the exporter. As an alternative to arbitrary strings causing a blowout of time-series, perhaps we could allow a string->int mapping in the config file that is user-configurable? That way we can allow the user to map a value such as healthState into an integer scheme of their choosing.

**Comment by russgold** [comment]
This is now in the main branch and will be included in the next release. With this config
```
queries:
- prefix: wls_server_
  key: name
  keyName: location
  applicationRuntimes:
    key: name
    selectedKeys: [jms-internal-notran-adp, jms-internal-xa-adp, wls-exporter]
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: wls_webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount]
      **stringValues:
        status: [deployed, undeployed]**
      servlets:
        prefix: wls_servlet_
        key: servletName
```

we now get metrics
```
wls_webapp_config_status{domain="mydomain",location="myserver",app="wls-exporter",name="myserver_/wls-exporter"} 0
```
