### ISSUE TITLE
Configuration item domainQualifier: true causes wrong formatted metric

### ISSUE THREAD

**Issue by DirkNachbar** [oracle/weblogic-monitoring-exporter#82]
Hi,

I am using the weblogic-monitoring-exporter 1.1.1, everything works fine unless I am setting the configuration item `domainQualifier: true` in my yaml file. As soon as I define `domainQualifier: true` the weblogic-monitoring-exporter is generating a wrong metric:
`name{domain="demo_domain"} demo_domain
wls_server_activation_time{domain="demo_domain",location="DemoAdminServer"} 1581419617765
wls_server_admin_server_listen_port{domain="demo_domain",location="DemoAdminServer"} 7001
wls_server_open_sockets_current_count{domain="demo_domain",location="DemoAdminServer"} 4
wls_server_state_val{domain="demo_domain",location="DemoAdminServer"} 2`

The first line `name{domain="demo_domain"} demo_domain` is causing following error in Prometheus: `level=warn ts=2020-02-11T11:17:44.919Z caller=scrape.go:930 component="scrape manager" scrape_pool=WebLogic target=http://172.17.0.1:7001/wls-exporter/metrics msg="append failed" err="unsupported character in float"`.
The afterwards following metric lines are containing the domain as expected.

Cheers
Dirk

**Comment by russgold** [comment]
What is your full yaml? It looks as though you are defining name as a metric.

**Comment by DirkNachbar** [comment]
Hi Russ,

here my yaml file:

===================================
```
metricsNameSnakeCase: true
domainQualifier: true
queries:
- key: name
  keyName: location
  prefix: wls_server_
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      prefix: wls_webapp_config_
      type: WebAppComponentRuntime
      key: name
      values: [deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount]
      servlets:
        prefix: wls_servlet_
        key: servletName
- JVMRuntime:
    prefix: wls_jvm_
    key: name
- executeQueueRuntimes:
    prefix: wls_socketmuxer_
    key: name
    values: [pendingRequestCurrentCount]
- workManagerRuntimes:
    prefix: wls_workmanager_
    key: name
    values: [stuckThreadCount, pendingRequests, completedRequests]
- threadPoolRuntime:
    prefix: wls_threadpool_
    key: name
    values: [executeThreadTotalCount, queueLength, stuckThreadCount, hoggingThreadCount]
- JMSRuntime:
    key: name
    keyName: jmsruntime
    prefix: wls_jmsruntime_
    JMSServers:
      prefix: wls_jms_
      key: name
      keyName: jmsserver
      destinations:
        prefix: wls_jms_dest_
        key: name
        keyName: destination

- persistentStoreRuntimes:
    prefix: wls_persistentstore_
    key: name
- JDBCServiceRuntime:
    JDBCDataSourceRuntimeMBeans:
      prefix: wls_datasource_
      key: name
- JTARuntime:
    prefix: wls_jta_
    key: name
```
===============================

When I remove the line ```domainQualifier: true``` and generate the war file newly without the line ```domainQualifier: true``` everything works fine, only when the line ```domainQualifier: true``` is present the wrongly formatted metric ```name{domain="demo_domain"} demo_domain``` is generated.

Cheers
Dirk
