### ISSUE TITLE
How to get weblogic_clusterName

### ISSUE THREAD

**Issue by senthil13** [oracle/weblogic-monitoring-exporter#89]
Hi Team,
How to get the cluster name in the metrics `weblogic_clusterName` ? 

`wls_jvm_uptime ` it provides the domain name and the  server name but not the cluster name,  Please direct me where from I can get the cluster name. 

`wls_jvm_uptime{domain="demo_domain",server="managedserver_1"} 338725691`

**Comment by marinakog** [comment]
check configuration provided by endtoend sample https://github.com/oracle/weblogic-monitoring-exporter/blob/master/samples/kubernetes/end2end/dashboard/exporter-config.yaml. Generated in Grafana dashboard uses that metrics ("expr": "count(count (wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (name))",)

**Comment by senthil13** [comment]
End2End sample for Kubernetes, I am having standalone domain running on Linux VMs. Even i used the config yaml provided at [Config.yaml](https://github.com/oracle/weblogic-monitoring-exporter/blob/master/samples/kubernetes/end2end/dashboard/exporter-config.yaml ) its not exporting the cluster name.

Thanks

**Comment by ipapakri** [comment]
Hi,

I was having the same problem. You have to add a label with the domain name as a static config in the prometheus yaml file. So in the yaml file you should have something like the following:
```
- job_name: <yourJobName>
    scrape_interval: 5s
    metrics_path: <your metrics path>
    static_configs:
    - targets: ['<your target url>']
      labels:
        weblogic_clusterName: '<your cluster name>'
        weblogic_domainName: '<your domain name>'
        weblogic_domainUID: '<your domain UID>'
        weblogic_serverName: '<your server name>'
```
You can add multiple targets and labels under the same job, have a look here [https://stackoverflow.com/a/55700165](https://stackoverflow.com/a/55700165)
