### ISSUE TITLE
JDBC Numeric to state mapping

### ISSUE THREAD

**Issue by senthil13** [oracle/weblogic-monitoring-exporter#95]
Hi Team,
I am searching for a mapping between the numeric value I am getting from wls-exporter for wls_datasource_deployment_state to the actual state. I am unable to find anywhere, could you please point me the document? 

`wls_datasource_deployment_state{domain="demo_domain",server="managedServer_1",name="jdbc.sample.pool"} 2`

[JDBC](https://docs.oracle.com/cd/E50629_01/wls/WLAPI/weblogic/management/runtime/JDBCDataSourceRuntimeMBean.html#getState())

```
Running 
Suspended
Shutdown
Overloaded
Unknown
```

**Comment by lennyphan** [comment]
Couldn't find any documentation but here is the mapping:

RUNNING - 0
SUSPENDED - 1
SHUTDOWN - 2
OVERLOADED -3
UNKNOWN - 4

**Comment by senthil13** [comment]
Hi @lennyphan  - Seems to be its not, 2 Means RUNNING. Why I am saying this is, Currently the state is 2 and in admin console the connection pool is RUNNING state. Which is similar to the `wls_server_state_val` metrics.

**Comment by lennyphan** [comment]
can you upload your exporter config so we can see the exact mbean you're getting stats from?

**Comment by lennyphan** [comment]
https://docs.oracle.com/cd/E50629_01/wls/WLAPI/index.html, take a look at ComponentRuntimeMBean

**Comment by senthil13** [comment]
Below is the config file.

```
metricsNameSnakeCase: true
domainQualifier: true
queries:
- key: name
  keyName: server
  prefix: wls_server_
  JDBCServiceRuntime:
    JDBCDataSourceRuntimeMBeans:
      prefix: wls_datasource_
      key: name
      values: [deploymentState, currCapacity, leakedConnectionCount, numAvailable, waitingForConnectionCurrentCount,connectionsCurrentCount,connectionsTotalCount,activeConnectionsCurrentCount,connectionDelayTime]
```
its --> JDBCDataSourceRuntimeMBean which only has below states

```
getState
String getState()
The current state of the data source.

Possible states are:

Running - the data source is enabled (deployed and not Suspended). This is the normal state of the data source. This state includes conditions when the database server is not available and the data source is created (creation retry must be enabled) or when all connections have failed connection tests (on creation, on reserve, or periodic testing).
Suspended - the data source has been disabled.
Shutdown - the data source is shutdown and all database connections have been closed.
Overloaded - all resources in pool are in use.
Unknown - the data source state is unknown.
Returns:
Current state of the connection pool.
```
